// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Enzyme = require("enzyme");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var App$ReasonReactRealworldExampleApp = require("../App.bs.js");

describe("App component", (function () {
        return Jest.test("renders without crashing", (function () {
                      var wrapper = Enzyme.mount(ReasonReact.element(undefined, undefined, App$ReasonReactRealworldExampleApp.make(/* array */[])));
                      return Jest.ExpectJs[/* toMatchSnapshot */16](Jest.Expect[/* expect */0](wrapper));
                    }));
      }));

describe("makeLinkClass", (function () {
        Jest.test("append \"active\" if current and target is same ", (function () {
                var actual = App$ReasonReactRealworldExampleApp.makeLinkClass(/* Home */0, /* Home */0);
                return Jest.Expect[/* toBe */2]("nav-link active", Jest.Expect[/* expect */0](actual));
              }));
        return Jest.test("append empty string if current and target is not same", (function () {
                      var actual = App$ReasonReactRealworldExampleApp.makeLinkClass(/* Home */0, /* Login */1);
                      return Jest.Expect[/* toBe */2]("nav-link", Jest.Expect[/* expect */0](actual));
                    }));
      }));

/*  Not a pure module */
