// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var API$ReasonReactRealworldExampleApp = require("./API.bs.js");
var Home$ReasonReactRealworldExampleApp = require("./Home.bs.js");
var Login$ReasonReactRealworldExampleApp = require("./Login.bs.js");
var Utils$ReasonReactRealworldExampleApp = require("./Utils.bs.js");
var Editor$ReasonReactRealworldExampleApp = require("./Editor.bs.js");
var Article$ReasonReactRealworldExampleApp = require("./Article.bs.js");
var Decoder$ReasonReactRealworldExampleApp = require("./Decoder.bs.js");
var Profile$ReasonReactRealworldExampleApp = require("./Profile.bs.js");
var Register$ReasonReactRealworldExampleApp = require("./Register.bs.js");
var Settings$ReasonReactRealworldExampleApp = require("./Settings.bs.js");
var PrivateRoute$ReasonReactRealworldExampleApp = require("./PrivateRoute.bs.js");

function makeLinkClass(current, target) {
  var match = current === target;
  return "nav-link" + (
          match ? " active" : ""
        );
}

function urlToRoute(url) {
  var hash = url[/* hash */1].split("/");
  var len = hash.length;
  if (len >= 5) {
    return /* Home */0;
  } else {
    switch (len) {
      case 0 : 
      case 1 : 
          return /* Home */0;
      case 2 : 
          var match = hash[0];
          if (match === "") {
            var match$1 = hash[1];
            switch (match$1) {
              case "editor" : 
                  return /* Editor */Block.__(0, [undefined]);
              case "login" : 
                  return /* Login */1;
              case "register" : 
                  return /* Register */2;
              case "settings" : 
                  return /* Settings */3;
              default:
                return /* Home */0;
            }
          } else {
            return /* Home */0;
          }
      case 3 : 
          var match$2 = hash[0];
          if (match$2 === "") {
            var match$3 = hash[1];
            switch (match$3) {
              case "article" : 
                  var slug = hash[2];
                  return /* Article */Block.__(1, [slug]);
              case "editor" : 
                  var slug$1 = hash[2];
                  return /* Editor */Block.__(0, [slug$1]);
              case "profile" : 
                  var author = hash[2];
                  return /* Profile */Block.__(2, [/* Author */Block.__(0, [author])]);
              default:
                return /* Home */0;
            }
          } else {
            return /* Home */0;
          }
      case 4 : 
          var match$4 = hash[0];
          if (match$4 === "") {
            var match$5 = hash[1];
            if (match$5 === "profile") {
              var author$1 = hash[2];
              var match$6 = hash[3];
              if (match$6 === "favorites") {
                return /* Profile */Block.__(2, [/* Favorited */Block.__(1, [author$1])]);
              } else {
                return /* Home */0;
              }
            } else {
              return /* Home */0;
            }
          } else {
            return /* Home */0;
          }
      
    }
  }
}

function getUser(_, param) {
  var send = param[/* send */3];
  Curry._1(send, /* UpdateUser */Block.__(0, [/* Loading */1]));
  API$ReasonReactRealworldExampleApp.user(/* () */0).then((function (result) {
            if (result.tag) {
              Curry._1(send, /* UpdateUser */Block.__(0, [/* Failure */Block.__(0, ["failed to get user data"])]));
            } else {
              var user = Json_decode.field("user", Decoder$ReasonReactRealworldExampleApp.user, result[0]);
              Curry._1(send, /* UpdateUser */Block.__(0, [/* Success */Block.__(1, [user])]));
            }
            return Promise.resolve(/* () */0);
          })).catch((function () {
          Curry._1(send, /* UpdateUser */Block.__(0, [/* Failure */Block.__(0, ["failed to get user data"])]));
          return Promise.resolve(/* () */0);
        }));
  return /* () */0;
}

function logoutUser(_, param) {
  return Curry._1(param[/* send */3], /* Logout */0);
}

var component = ReasonReact.reducerComponent("App");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (param) {
              var send = param[/* send */3];
              var urlWatcherId = ReasonReact.Router[/* watchUrl */1]((function (url) {
                      return Curry._1(send, /* ChangeRoute */Block.__(1, [urlToRoute(url)]));
                    }));
              Curry._1(param[/* onUnmount */4], (function () {
                      return ReasonReact.Router[/* unwatchUrl */2](urlWatcherId);
                    }));
              return Curry._2(param[/* handle */0], getUser, /* () */0);
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              var state = param[/* state */1];
              var user = state[/* user */1];
              var route = state[/* route */0];
              var handle = param[/* handle */0];
              var tmp;
              if (typeof user === "number" || !user.tag) {
                tmp = Utils$ReasonReactRealworldExampleApp.nullEl;
              } else {
                var tmp$1;
                tmp$1 = typeof route === "number" || route.tag ? "" : " active";
                tmp = React.createElement("li", {
                      className: "nav-item"
                    }, React.createElement("a", {
                          className: "nav-link" + tmp$1,
                          href: "/#/editor"
                        }, React.createElement("i", {
                              className: "ion-compose"
                            }), Utils$ReasonReactRealworldExampleApp.strEl(" New Post")));
              }
              var tmp$2;
              tmp$2 = typeof user === "number" || !user.tag ? Utils$ReasonReactRealworldExampleApp.nullEl : React.createElement("li", {
                      className: "nav-item"
                    }, React.createElement("a", {
                          className: makeLinkClass(route, /* Settings */3),
                          href: "/#/settings"
                        }, React.createElement("i", {
                              className: "ion-gear-a"
                            }), Utils$ReasonReactRealworldExampleApp.strEl(" Settings")));
              var tmp$3;
              tmp$3 = typeof user === "number" || user.tag ? Utils$ReasonReactRealworldExampleApp.nullEl : React.createElement("li", {
                      className: "nav-item"
                    }, React.createElement("a", {
                          className: makeLinkClass(route, /* Login */1),
                          href: "/#/login"
                        }, Utils$ReasonReactRealworldExampleApp.strEl("Sign in")));
              var tmp$4;
              if (typeof user === "number" || user.tag !== 1) {
                tmp$4 = Utils$ReasonReactRealworldExampleApp.nullEl;
              } else {
                var match = user[0];
                var username = match[/* username */7];
                var image = match[/* image */4];
                tmp$4 = React.createElement("li", {
                      className: "nav-item"
                    }, React.createElement("a", {
                          className: makeLinkClass(route, /* Profile */Block.__(2, [/* Author */Block.__(0, [username])])),
                          href: "/#/profile/" + username
                        }, image !== undefined ? React.createElement("img", {
                                className: "user-pic",
                                src: image
                              }) : Utils$ReasonReactRealworldExampleApp.nullEl, Utils$ReasonReactRealworldExampleApp.strEl(username)));
              }
              var tmp$5;
              if (typeof route === "number") {
                switch (route) {
                  case 0 : 
                      tmp$5 = ReasonReact.element(undefined, undefined, Home$ReasonReactRealworldExampleApp.make(user, /* array */[]));
                      break;
                  case 1 : 
                      tmp$5 = ReasonReact.element(undefined, undefined, Login$ReasonReactRealworldExampleApp.make(Curry._1(handle, getUser), /* array */[]));
                      break;
                  case 2 : 
                      tmp$5 = ReasonReact.element(undefined, undefined, Register$ReasonReactRealworldExampleApp.make(Curry._1(handle, getUser), /* array */[]));
                      break;
                  case 3 : 
                      tmp$5 = ReasonReact.element(undefined, undefined, PrivateRoute$ReasonReactRealworldExampleApp.make(user, (function (userData) {
                                  return ReasonReact.element(undefined, undefined, Settings$ReasonReactRealworldExampleApp.make(Curry._1(handle, logoutUser), userData, /* array */[]));
                                })));
                      break;
                  
                }
              } else {
                switch (route.tag | 0) {
                  case 0 : 
                      tmp$5 = ReasonReact.element(undefined, undefined, Editor$ReasonReactRealworldExampleApp.make(route[0], /* array */[]));
                      break;
                  case 1 : 
                      tmp$5 = ReasonReact.element(undefined, undefined, Article$ReasonReactRealworldExampleApp.make(user, route[0], /* array */[]));
                      break;
                  case 2 : 
                      tmp$5 = ReasonReact.element(undefined, undefined, Profile$ReasonReactRealworldExampleApp.make(user, route[0], /* array */[]));
                      break;
                  
                }
              }
              return React.createElement("div", undefined, React.createElement("nav", {
                              className: "navbar navbar-light"
                            }, React.createElement("div", {
                                  className: "container"
                                }, React.createElement("a", {
                                      className: "navbar-brand",
                                      href: "/#/"
                                    }, Utils$ReasonReactRealworldExampleApp.strEl("maestro content")), React.createElement("ul", {
                                      className: "nav navbar-nav pull-xs-right"
                                    }, React.createElement("li", {
                                          className: "nav-item"
                                        }, React.createElement("a", {
                                              className: makeLinkClass(route, /* Home */0),
                                              href: "/#/"
                                            }, Utils$ReasonReactRealworldExampleApp.strEl("Home"))), tmp, tmp$2, tmp$3, tmp$4))), tmp$5, React.createElement("footer", undefined, React.createElement("div", {
                                  className: "container"
                                }, React.createElement("a", {
                                      className: "logo-font",
                                      href: "/"
                                    }, Utils$ReasonReactRealworldExampleApp.strEl("maestro content")), React.createElement("span", {
                                      className: "attribution"
                                    }, Utils$ReasonReactRealworldExampleApp.strEl("Based on an demo by "), React.createElement("a", {
                                          href: "https://thinkster.io"
                                        }, Utils$ReasonReactRealworldExampleApp.strEl("Thinkster")), Utils$ReasonReactRealworldExampleApp.strEl(".")))));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* route */urlToRoute(ReasonReact.Router[/* dangerouslyGetInitialUrl */3](/* () */0)),
                      /* user : NotAsked */0
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (typeof action === "number") {
                Utils$ReasonReactRealworldExampleApp.setCookie("token", "");
                return /* UpdateWithSideEffects */Block.__(2, [
                          /* record */[
                            /* route */state[/* route */0],
                            /* user : NotAsked */0
                          ],
                          (function () {
                              return ReasonReact.Router[/* push */0]("/#/");
                            })
                        ]);
              } else if (action.tag) {
                return /* UpdateWithSideEffects */Block.__(2, [
                          /* record */[
                            /* route */action[0],
                            /* user */state[/* user */1]
                          ],
                          (function (param) {
                              var match = param[/* state */1][/* user */1];
                              if (typeof match === "number" && match === 0) {
                                return Curry._2(param[/* handle */0], getUser, /* () */0);
                              } else {
                                return /* () */0;
                              }
                            })
                        ]);
              } else {
                return /* Update */Block.__(0, [/* record */[
                            /* route */state[/* route */0],
                            /* user */action[0]
                          ]]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var $$default = ReasonReact.wrapReasonForJs(component, (function () {
        return make(/* array */[]);
      }));

exports.makeLinkClass = makeLinkClass;
exports.urlToRoute = urlToRoute;
exports.getUser = getUser;
exports.logoutUser = logoutUser;
exports.component = component;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* component Not a pure module */
