// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Utils$ReasonReactRealworldExampleApp = require("./Utils.bs.js");

var component = ReasonReact.statelessComponent("ArticleItem");

function make(value, onFavoriteClick, $staropt$star, _) {
  var favoriteDisabled = $staropt$star !== undefined ? $staropt$star : false;
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              var author = value[/* author */9];
              var favorited = value[/* favorited */7];
              var slug = value[/* slug */0];
              return React.createElement("div", {
                          className: "article-preview"
                        }, React.createElement("div", {
                              className: "article-meta"
                            }, React.createElement("a", {
                                  href: "/#/profile/" + author[/* username */0]
                                }, React.createElement("img", {
                                      src: author[/* image */2]
                                    })), React.createElement("div", {
                                  className: "info"
                                }, React.createElement("a", {
                                      className: "author",
                                      href: "/#/profile/" + author[/* username */0]
                                    }, Utils$ReasonReactRealworldExampleApp.strEl(author[/* username */0])), React.createElement("span", {
                                      className: "date"
                                    }, Utils$ReasonReactRealworldExampleApp.strEl(value[/* createdAt */5].toUTCString()))), React.createElement("button", {
                                  className: "btn  btn-sm pull-xs-right " + (
                                    favorited ? "btn-primary" : "btn-outline-primary"
                                  ),
                                  disabled: favoriteDisabled,
                                  onClick: (function () {
                                      if (favoriteDisabled) {
                                        return /* () */0;
                                      } else {
                                        return Curry._1(onFavoriteClick, /* tuple */[
                                                    slug,
                                                    !favorited
                                                  ]);
                                      }
                                    })
                                }, React.createElement("i", {
                                      className: "ion-heart"
                                    }), Utils$ReasonReactRealworldExampleApp.strEl(" " + String(value[/* favoritesCount */8])))), React.createElement("a", {
                              className: "preview-link",
                              href: "/#/article/" + slug
                            }, React.createElement("h1", undefined, Utils$ReasonReactRealworldExampleApp.strEl(value[/* title */1])), React.createElement("p", undefined, Utils$ReasonReactRealworldExampleApp.strEl(value[/* description */2])), React.createElement("span", undefined, Utils$ReasonReactRealworldExampleApp.strEl("Read more..."))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
