// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function author(json) {
  return /* record */[
          /* username */Json_decode.field("username", Json_decode.string, json),
          /* bio */Json_decode.field("bio", (function (param) {
                  return Json_decode.optional(Json_decode.string, param);
                }), json),
          /* image */Json_decode.field("image", Json_decode.string, json),
          /* following */Json_decode.field("following", Json_decode.bool, json)
        ];
}

function article(json) {
  return /* record */[
          /* slug */Json_decode.field("slug", Json_decode.string, json),
          /* title */Json_decode.field("title", Json_decode.string, json),
          /* description */Belt_Option.getWithDefault(Json_decode.field("description", (function (param) {
                      return Json_decode.optional(Json_decode.string, param);
                    }), json), ""),
          /* body */Json_decode.field("body", Json_decode.string, json),
          /* tagList */Belt_List.fromArray(Json_decode.field("tagList", (function (param) {
                      return Json_decode.array(Json_decode.string, param);
                    }), json)),
          /* createdAt */Json_decode.field("createdAt", Json_decode.date, json),
          /* updatedAt */Json_decode.field("updatedAt", Json_decode.date, json),
          /* favorited */Json_decode.field("favorited", Json_decode.bool, json),
          /* favoritesCount */Json_decode.field("favoritesCount", Json_decode.$$int, json),
          /* author */Json_decode.field("author", author, json)
        ];
}

function file(json) {
  return /* record */[
          /* createDate */Json_decode.field("createDate", Json_decode.date, json),
          /* createUser */Json_decode.field("createUser", Json_decode.string, json),
          /* storedFileName */Json_decode.field("storedFileName", Json_decode.string, json),
          /* fileSize */Json_decode.field("fileSize", Json_decode.$$int, json),
          /* folder */Json_decode.field("folder", Json_decode.string, json),
          /* guid */Json_decode.field("guid", Json_decode.string, json),
          /* name */Json_decode.field("name", Json_decode.string, json),
          /* sortOrder */Json_decode.field("sortOrder", Json_decode.$$int, json),
          /* updateDate */Json_decode.field("updateDate", Json_decode.date, json)
        ];
}

function profile(json) {
  return /* record */[
          /* username */Json_decode.field("username", Json_decode.string, json),
          /* bio */Json_decode.field("bio", (function (param) {
                  return Json_decode.optional(Json_decode.string, param);
                }), json),
          /* image */Json_decode.field("image", Json_decode.string, json),
          /* following */Json_decode.field("following", Json_decode.bool, json)
        ];
}

function comment(json) {
  return /* record */[
          /* id */Json_decode.field("id", Json_decode.$$int, json),
          /* createdAt */Json_decode.field("createdAt", Json_decode.date, json),
          /* updatedAt */Json_decode.field("updatedAt", Json_decode.date, json),
          /* body */Json_decode.field("body", Json_decode.string, json),
          /* author */Json_decode.field("author", author, json)
        ];
}

function user(json) {
  return /* record */[
          /* bio */Json_decode.field("bio", (function (param) {
                  return Json_decode.optional(Json_decode.string, param);
                }), json),
          /* email */Json_decode.field("email", Json_decode.string, json),
          /* image */Json_decode.field("image", (function (param) {
                  return Json_decode.optional(Json_decode.string, param);
                }), json),
          /* token */Json_decode.field("token", Json_decode.string, json),
          /* username */Json_decode.field("username", Json_decode.string, json)
        ];
}

exports.author = author;
exports.article = article;
exports.file = file;
exports.profile = profile;
exports.comment = comment;
exports.user = user;
/* No side effect */
