// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Utils$ReasonReactRealworldExampleApp = require("./Utils.bs.js");

var component = ReasonReact.statelessComponent("FileItem");

function make(value, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: "file-preview"
                        }, React.createElement("div", {
                              className: "file-meta"
                            }, React.createElement("a", {
                                  className: "preview-link",
                                  href: "/#/details/" + value[/* guid */5]
                                }, React.createElement("p", undefined, Utils$ReasonReactRealworldExampleApp.strEl(value[/* folder */4]), Utils$ReasonReactRealworldExampleApp.strEl(value[/* name */6])))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
