// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Utils$ReasonReactRealworldExampleApp = require("./Utils.bs.js");
var Errors$ReasonReactRealworldExampleApp = require("./Errors.bs.js");

var component = ReasonReact.statelessComponent("FormBody");

function make(username, onUsernameChange, onUsernameBlur, email, onEmailChange, onEmailBlur, password, onPasswordChange, onPasswordBlur, onSubmit, errors, route, submitting, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              var register = route === /* Register */2;
              return React.createElement("div", {
                          className: "auth-page"
                        }, React.createElement("div", {
                              className: "container page"
                            }, React.createElement("div", {
                                  className: "row"
                                }, React.createElement("div", {
                                      className: "col-md-6 offset-md-3 col-xs-12"
                                    }, React.createElement("h1", {
                                          className: "text-xs-center"
                                        }, Utils$ReasonReactRealworldExampleApp.strEl(register ? "Sign up" : "Sign in")), ReasonReact.element(undefined, undefined, Errors$ReasonReactRealworldExampleApp.make(errors, /* array */[])), React.createElement("form", {
                                          onSubmit: onSubmit
                                        }, register ? React.createElement("fieldset", {
                                                className: "form-group"
                                              }, React.createElement("input", {
                                                    className: "form-control form-control-lg",
                                                    disabled: submitting,
                                                    placeholder: "Your Name",
                                                    type: "text",
                                                    value: username,
                                                    onBlur: onUsernameBlur,
                                                    onChange: onUsernameChange
                                                  })) : Utils$ReasonReactRealworldExampleApp.nullEl, React.createElement("fieldset", {
                                              className: "form-group"
                                            }, React.createElement("input", {
                                                  className: "form-control form-control-lg",
                                                  disabled: submitting,
                                                  placeholder: "UIN",
                                                  type: "text",
                                                  value: email,
                                                  onBlur: onEmailBlur,
                                                  onChange: onEmailChange
                                                })), React.createElement("fieldset", {
                                              className: "form-group"
                                            }, React.createElement("input", {
                                                  className: "form-control form-control-lg",
                                                  disabled: submitting,
                                                  placeholder: "Password",
                                                  type: "password",
                                                  value: password,
                                                  onBlur: onPasswordBlur,
                                                  onChange: onPasswordChange
                                                })), React.createElement("button", {
                                              className: "btn btn-lg btn-primary pull-xs-right",
                                              disabled: submitting
                                            }, Utils$ReasonReactRealworldExampleApp.strEl(register ? (
                                                    submitting ? "Submitting..." : "Sign up"
                                                  ) : (
                                                    submitting ? "Submitting..." : "Sign in"
                                                  ))))))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
