// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

var component = ReasonReact.statelessComponent("Img");

function make($staropt$star, $staropt$star$1, $staropt$star$2, $staropt$star$3, _) {
  var src = $staropt$star !== undefined ? Js_primitive.valFromOption($staropt$star) : undefined;
  var width = $staropt$star$1 !== undefined ? $staropt$star$1 : 30;
  var height = $staropt$star$2 !== undefined ? $staropt$star$2 : 30;
  var className = $staropt$star$3 !== undefined ? $staropt$star$3 : "";
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("img", {
                          className: className,
                          src: Belt_Option.getWithDefault(src, "//placehold.it/" + (String(width) + ("x" + String(height))))
                        });
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
