// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");

function make(message, _) {
  return new Error(Js_undefined.fromOption(message));
}

var $$Error$1 = /* module */[/* make */make];

var Mock = /* module */[];

function mockResponse(body, status, statusText, _) {
  var tmp = { };
  if (status !== undefined) {
    tmp.status = Js_primitive.valFromOption(status);
  }
  if (statusText !== undefined) {
    tmp.statusText = Js_primitive.valFromOption(statusText);
  }
  fetch.mockResponse(body, tmp);
  return /* () */0;
}

exports.$$Error = $$Error$1;
exports.Mock = Mock;
exports.mockResponse = mockResponse;
/* No side effect */
