// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Utils$ReasonReactRealworldExampleApp = require("./Utils.bs.js");

var component = ReasonReact.statelessComponent("Pagination");

function make(currentPage, totalCount, perPage, onPageClick, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("nav", undefined, React.createElement("ul", {
                              className: "pagination"
                            }, Utils$ReasonReactRealworldExampleApp.arrayEl(Belt_List.toArray(Belt_List.mapU(Belt_List.makeBy(Math.ceil(totalCount / perPage) | 0, (function (i) {
                                                return i + 1 | 0;
                                              })), (function (page) {
                                            var key = String(page);
                                            var match = page === currentPage;
                                            return React.createElement("li", {
                                                        key: key,
                                                        className: "page-item" + (
                                                          match ? " active" : ""
                                                        ),
                                                        onClick: (function ($$event) {
                                                            $$event.preventDefault();
                                                            return Curry._1(onPageClick, page);
                                                          })
                                                      }, React.createElement("a", {
                                                            className: "page-link",
                                                            href: "#" + key
                                                          }, Utils$ReasonReactRealworldExampleApp.strEl(key)));
                                          }))))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
